---


- name: Adding Jenkins Repo Key
  ansible.builtin.shell: |
      curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-archive-keyring.asc > /dev/null

- name: Adding Jenkins Repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-archive-keyring.asc] https://pkg.jenkins.io/debian binary/"
    state: present

- name: Updating Cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Jenkins
  ansible.builtin.apt:
    name: jenkins
    state: present


- name: Start and enable Jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: true


- name: Allow traffic on Jenkins port (8080)
  ansible.builtin.ufw:
    rule: allow
    port: 8080
    proto: tcp
