pipeline {
    agent any

    environment {
        DOCKER_CREDENTIALS = credentials('Docker-Hub-Repo')
        KUBE_CONFIG = credentials('kubeconfig-file')
        DOCKER_IMAGE = 'gohary101/jenkins_repo101:2.1'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/abdulrahman-elgohary/ivolve-training.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t ${DOCKER_IMAGE} Jenkins/Lab-23/.
                '''
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                sh '''
                echo $PASSWORD | docker login -u $USERNAME --password-stdin
                docker push ${DOCKER_IMAGE}
                '''
            }
        }

        stage('Update Deployment File') {
            steps {
                sh '''
                sed -i 's|image: .*|image: ${DOCKER_IMAGE}|' deployment.yaml
                '''
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                withKubeConfig([credentialsId: 'kubeconfig-file']) {
                    sh 'kubectl apply -f deployment.yaml'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution complete!'
        }
    }
}
