apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /home/mav/.minikube/ca.crt
    server: https://192.168.58.2:8443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: jenkins
  name: jenkins-context
current-context: jenkins-context
users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ik5NOTRuQ0VGODNQbEgzS1dWY0pXRlJFTVZmRGdrZWJ0ZEVOUTJkaXBQSWcifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzM0MDk0NTUzLCJpYXQiOjE3MzQwOTA5NTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMmVkODE3YzktNmU5Zi00OWUwLWI1NjUtMzAyNTE1NjNkNzFhIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiI5NzRmNmIzNS00N2NhLTQ4OTEtODU0MC01Nzc0MzZhMDEwYWEifX0sIm5iZiI6MTczNDA5MDk1Mywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6amVua2lucyJ9.IngXhM_OQXQIdUdeoQH3azZxzHJEiY1qjyq8yFVsFbzO9yWrLTH5rzQbB6sJ-uEpKEqw5dWULILpbg2aw8zTk4whFTD4LICR7byLZTwJss4ouSgEJVfYU516r7WTKD4wkkchtmjk4zsHEEq8jlcZHCIKhdsvDEgegzYJ0rhQvJjSrqClQ0EyBl5AM2gM-2iWBos3Tkruf-xN109Y0CvN2AH_51fgS3AFB3Me9GfPguKOzFXJcluHaXAF4tMLuylSbg__BnPfDUN236fi5Sdezm8ZA_iG2sFqmNSntBCDjbQAgChCoQmnGf6eMfr73rzjUhPFFgv45CNbNSCOoDFL9w
